version: '3.5'

services:
  ravendb:
    container_name: marketplace-ravendb
    image: ravendb/ravendb:5.4-ubuntu-latest
    ports:
      - "8080:8080"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"
